# Generated by Django 4.1.5 on 2023-01-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_firstname', models.CharField(max_length=20)),
                ('booking_lastname', models.CharField(max_length=20)),
                ('booking_email', models.CharField(max_length=100)),
                ('booking_phone', models.CharField(max_length=20)),
                ('booking_fromaddress', models.CharField(max_length=20)),
                ('booking_toaddress', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_message', models.CharField(max_length=500)),
            ],
        ),
    ]
