# Generated by Django 4.1.5 on 2023-01-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_booking_booking_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_email', models.CharField(max_length=100)),
                ('c_phno', models.CharField(max_length=20)),
                ('c_message', models.CharField(max_length=500)),
            ],
        ),
    ]
