# Generated by Django 4.1.5 on 2023-02-02 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
