# Generated by Django 4.1.5 on 2023-02-05 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='new_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
